import { TicketCategory, TicketPriority } from "@prisma/client";

export const ticketRules = [
  // ACCESS
  {
    keywords: [
      "password",
      "login",
      "access",
      "reset",
      "signin",
      "sign in",
      "authentication",
      "auth",
      "mfa",
      "2fa",
      "otp",
      "locked",
      "lockout",
      "account locked",
      "permission",
      "permissions",
      "privilege",
      "unauthorized",
      "forbidden",
      "credential",
      "credentials",
      "user access",
      "role",
      "roles",
    ],
    category: TicketCategory.ACCESS,
    priority: TicketPriority.P2,
  },

  // NETWORK
  {
    keywords: [
      "network",
      "server",
      "down",
      "crash",
      "unreachable",
      "internet",
      "wifi",
      "vpn",
      "latency",
      "timeout",
      "dns",
      "gateway",
      "router",
      "switch",
      "packet loss",
      "connection",
      "connectivity",
      "slow network",
      "outage",
      "bandwidth",
      "proxy",
      "firewall",
      "unable to connect",
      "disconnect",
      "offline",
      "socket",
      "tcp",
      "ip address",
      "ping",
    ],
    category: TicketCategory.NETWORK,
    priority: TicketPriority.P1,
  },

  // SOFTWARE
  {
    keywords: [
      "install",
      "installation",
      "software",
      "application",
      "app",
      "bug",
      "error",
      "exception",
      "crash report",
      "failed",
      "failure",
      "upgrade",
      "update",
      "patch",
      "version",
      "runtime",
      "dependency",
      "npm",
      "package",
      "compile",
      "build",
      "deployment",
      "api",
      "database error",
      "sql error",
      "null pointer",
      "stack trace",
      "service error",
      "backend",
      "frontend",
    ],
    category: TicketCategory.SOFTWARE,
    priority: TicketPriority.P3,
  },

  // HARDWARE
  {
    keywords: [
      "laptop",
      "desktop",
      "monitor",
      "screen",
      "keyboard",
      "mouse",
      "printer",
      "scanner",
      "webcam",
      "headset",
      "speaker",
      "microphone",
      "battery",
      "charger",
      "power supply",
      "ram",
      "memory",
      "ssd",
      "hard disk",
      "hdd",
      "cpu",
      "motherboard",
      "usb",
      "device",
      "overheating",
      "hardware failure",
      "broken screen",
      "boot issue",
      "bios",
    ],
    category: TicketCategory.HARDWARE,
    priority: TicketPriority.P2,
  },
];